package com.example.quizit.Data;

import com.example.quizit.model.Answer;
import com.example.quizit.model.Player;
import com.example.quizit.model.Question;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

public class DataRepository {

    public List<Answer> _anwsers = new ArrayList<>();
    public ArrayList<Question> _questions = new ArrayList<>();
    public List<Player> _players = new ArrayList<>();

    public static List<Question> fullPool = new LinkedList<>();         //loading questions for the selected categories

    public static void LiteratureLoader() {
        Question temp = new Question();
        temp.setQuestion("Wer schrieb das Buch namens Faust?");                     //questions and answers generated by OpenAI's GPT-3.5
        temp.getAnswers().add("Johann Wolfgang von Goethe");                        //correct answer first!!
        temp.getAnswers().add("Thomas Brezina");
        temp.getAnswers().add("Friedrich Schiller");
        temp.getAnswers().add("Heinrich Heine");
        fullPool.add(temp);

        //copy following code for new question:
        temp = new Question();
        temp.setQuestion("Welcher der folgenden ist keine literarische Epoche?");
        temp.getAnswers().add("Rassismus");
        temp.getAnswers().add("Realismus");
        temp.getAnswers().add("Expressionismus");
        temp.getAnswers().add("Romantik");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Werk stammt von William Shakespeare?");
        temp.getAnswers().add("Romeo und Julia");
        temp.getAnswers().add("Harry Potter");
        temp.getAnswers().add("Der große Gatsby");
        temp.getAnswers().add("Krieg und Frieden");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer schrieb 'Die Odyssee'?");
        temp.getAnswers().add("Homer");
        temp.getAnswers().add("Virgil");
        temp.getAnswers().add("Dante Alighieri");
        temp.getAnswers().add("Hermann Hesse");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Buch wurde von Jane Austen geschrieben?");
        temp.getAnswers().add("Stolz und Vorurteil");
        temp.getAnswers().add("Der Graf von Monte Christo");
        temp.getAnswers().add("Faust");
        temp.getAnswers().add("Anna Karenina");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land spielt 'Die Verwandlung' von Franz Kafka?");
        temp.getAnswers().add("Tschechien");
        temp.getAnswers().add("Deutschland");
        temp.getAnswers().add("Österreich");
        temp.getAnswers().add("Russland");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer ist der Autor von '1984'?");
        temp.getAnswers().add("George Orwell");
        temp.getAnswers().add("Aldous Huxley");
        temp.getAnswers().add("Ray Bradbury");
        temp.getAnswers().add("Philip K. Dick");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Buch wird oft als 'Der Große Gatsby' bezeichnet?");
        temp.getAnswers().add("F. Scott Fitzgerald");
        temp.getAnswers().add("Ernest Hemingway");
        temp.getAnswers().add("Mark Twain");
        temp.getAnswers().add("J.D. Salinger");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer schrieb 'Die Leiden des jungen Werthers'?");
        temp.getAnswers().add("Johann Wolfgang von Goethe");
        temp.getAnswers().add("Franz Kafka");
        temp.getAnswers().add("Thomas Mann");
        temp.getAnswers().add("Friedrich Schiller");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist das bekannteste Werk von Leo Tolstoi?");
        temp.getAnswers().add("Krieg und Frieden");
        temp.getAnswers().add("Anna Karenina");
        temp.getAnswers().add("Auferstehung");
        temp.getAnswers().add("Kinderbuch");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Buch erzählt die Geschichte von Pip und Magwitch?");
        temp.getAnswers().add("Große Erwartungen");
        temp.getAnswers().add("Sturmhöhe");
        temp.getAnswers().add("Jane Eyre");
        temp.getAnswers().add("David Copperfield");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer schrieb 'Der kleine Prinz'?");
        temp.getAnswers().add("Antoine de Saint-Exupéry");
        temp.getAnswers().add("Jules Verne");
        temp.getAnswers().add("Hans Christian Andersen");
        temp.getAnswers().add("Gabriel García Márquez");
        fullPool.add(temp);
    }

    public static void geographyLoader() {
        Question temp = new Question();
        temp.setQuestion("Was ist die Hauptstadt von Finnland?");
        temp.getAnswers().add("Helsinki");                               //correct answer first!!
        temp.getAnswers().add("Oslo");
        temp.getAnswers().add("Litauen");
        temp.getAnswers().add("Stockholm");
        fullPool.add(temp);

        //copy following code for new question:
        temp = new Question();
        temp.setQuestion("Welche Sprache spricht man in Liechtenstein?");
        temp.getAnswers().add("Deutsch");
        temp.getAnswers().add("Französisch");
        temp.getAnswers().add("Englisch");
        temp.getAnswers().add("Türkisch");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Hauptstadt von Australien?");
        temp.getAnswers().add("Canberra");
        temp.getAnswers().add("Sydney");
        temp.getAnswers().add("Melbourne");
        temp.getAnswers().add("Perth");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Fluss fließt durch Berlin?");
        temp.getAnswers().add("Spree");
        temp.getAnswers().add("Donau");
        temp.getAnswers().add("Themse");
        temp.getAnswers().add("Seine");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Land hat die meisten Einwohner?");
        temp.getAnswers().add("China");
        temp.getAnswers().add("Indien");
        temp.getAnswers().add("USA");
        temp.getAnswers().add("Indonesien");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Ozean liegt östlich von Afrika?");
        temp.getAnswers().add("Indischer Ozean");
        temp.getAnswers().add("Atlantischer Ozean");
        temp.getAnswers().add("Pazifischer Ozean");
        temp.getAnswers().add("Südlicher Ozean");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt die Insel Kreta?");
        temp.getAnswers().add("Griechenland");
        temp.getAnswers().add("Italien");
        temp.getAnswers().add("Spanien");
        temp.getAnswers().add("Kroatien");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Land wird als das Land der aufgehenden Sonne bezeichnet?");
        temp.getAnswers().add("Japan");
        temp.getAnswers().add("China");
        temp.getAnswers().add("Korea");
        temp.getAnswers().add("Vietnam");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Meer liegt die Karibik?");
        temp.getAnswers().add("Atlantischer Ozean");
        temp.getAnswers().add("Indischer Ozean");
        temp.getAnswers().add("Pazifischer Ozean");
        temp.getAnswers().add("Karibisches Meer");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Fluss fließt durch Moskau?");
        temp.getAnswers().add("Moskwa");
        temp.getAnswers().add("Wolga");
        temp.getAnswers().add("Donau");
        temp.getAnswers().add("Seine");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Land wird auch als Neuseeland bekannt?");
        temp.getAnswers().add("Aotearoa");
        temp.getAnswers().add("Fidschi");
        temp.getAnswers().add("Papua-Neuguinea");
        temp.getAnswers().add("Vanuatu");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Land hat den Äquator?");
        temp.getAnswers().add("Ecuador");
        temp.getAnswers().add("Brasilien");
        temp.getAnswers().add("Kolumbien");
        temp.getAnswers().add("Peru");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Fluss fließt durch Kairo?");
        temp.getAnswers().add("Nil");
        temp.getAnswers().add("Amazonas");
        temp.getAnswers().add("Jangtse");
        temp.getAnswers().add("Ganges");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt die Serengeti?");
        temp.getAnswers().add("Tansania");
        temp.getAnswers().add("Kenia");
        temp.getAnswers().add("Südafrika");
        temp.getAnswers().add("Uganda");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Wüste erstreckt sich durch Nordamerika?");
        temp.getAnswers().add("Sonora-Wüste");
        temp.getAnswers().add("Gobi-Wüste");
        temp.getAnswers().add("Sahara");
        temp.getAnswers().add("Atacama-Wüste");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt der Ayers Rock?");
        temp.getAnswers().add("Australien");
        temp.getAnswers().add("Neuseeland");
        temp.getAnswers().add("Südafrika");
        temp.getAnswers().add("Indonesien");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Berg ist der höchste in Südamerika?");
        temp.getAnswers().add("Aconcagua");
        temp.getAnswers().add("Huascarán");
        temp.getAnswers().add("Fitz Roy");
        temp.getAnswers().add("Huayna Potosí");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt der Dachstein?");
        temp.getAnswers().add("Österreich");
        temp.getAnswers().add("Deutschland");
        temp.getAnswers().add("Schweiz");
        temp.getAnswers().add("Italien");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Fluss fließt durch Rom?");
        temp.getAnswers().add("Tiber");
        temp.getAnswers().add("Po");
        temp.getAnswers().add("Arno");
        temp.getAnswers().add("Rhein");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt die Stadt Kapstadt?");
        temp.getAnswers().add("Südafrika");
        temp.getAnswers().add("Kenia");
        temp.getAnswers().add("Nigeria");
        temp.getAnswers().add("Ägypten");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Ozean liegt die Inselgruppe Hawaii?");
        temp.getAnswers().add("Pazifischer Ozean");
        temp.getAnswers().add("Atlantischer Ozean");
        temp.getAnswers().add("Indischer Ozean");
        temp.getAnswers().add("Arktischer Ozean");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Berg ist der höchste in Afrika?");
        temp.getAnswers().add("Kilimandscharo");
        temp.getAnswers().add("Mount Kenya");
        temp.getAnswers().add("Ras Dashen");
        temp.getAnswers().add("Simien-Berge");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt die Halbinsel Kamtschatka?");
        temp.getAnswers().add("Russland");
        temp.getAnswers().add("Kanada");
        temp.getAnswers().add("Alaska (USA)");
        temp.getAnswers().add("Japan");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Land hat die meisten Inseln?");
        temp.getAnswers().add("Indonesien");
        temp.getAnswers().add("Schweden");
        temp.getAnswers().add("Philippinen");
        temp.getAnswers().add("Finnland");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Stadt wird auch als die Perle des Orients bezeichnet?");
        temp.getAnswers().add("Shanghai");
        temp.getAnswers().add("Kairo");
        temp.getAnswers().add("Bangkok");
        temp.getAnswers().add("Mumbai");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Land liegt die Atacama-Wüste?");
        temp.getAnswers().add("Chile");
        temp.getAnswers().add("Peru");
        temp.getAnswers().add("Argentinien");
        temp.getAnswers().add("Bolivien");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Fluss fließt durch Budapest?");
        temp.getAnswers().add("Donau");
        temp.getAnswers().add("Rhein");
        temp.getAnswers().add("Seine");
        temp.getAnswers().add("Wolga");
        fullPool.add(temp);
    }

    public static void mathLoader() {
        Question temp = new Question();
        temp.setQuestion("Wie nennt man eine Zahl, die sich nur durch 1 und sich selbst ohne Rest teilen lässt?");
        temp.getAnswers().add("Primzahl");                                  //correct answer first!!
        temp.getAnswers().add("Zusammengesetzte Zahl");
        temp.getAnswers().add("Gerade Zahl");
        temp.getAnswers().add("Ungerade Zahl");
        fullPool.add(temp);


        //copy following code for new question:
        temp = new Question();
        temp.setQuestion("Wie lautet das Ergebnis von 7 * 8?");
        temp.getAnswers().add("56");
        temp.getAnswers().add("64");
        temp.getAnswers().add("49");
        temp.getAnswers().add("42");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Quadratwurzel von 144?");
        temp.getAnswers().add("12");
        temp.getAnswers().add("10");
        temp.getAnswers().add("8");
        temp.getAnswers().add("16");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Löse die Gleichung: 2x + 5 = 15");
        temp.getAnswers().add("5");
        temp.getAnswers().add("10");
        temp.getAnswers().add("3");
        temp.getAnswers().add("7");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Summe der Innenwinkel in einem Dreieck?");
        temp.getAnswers().add("180 Grad");
        temp.getAnswers().add("90 Grad");
        temp.getAnswers().add("360 Grad");
        temp.getAnswers().add("120 Grad");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Fläche eines Rechtecks mit Länge 10 und Breite 5?");
        temp.getAnswers().add("50");
        temp.getAnswers().add("30");
        temp.getAnswers().add("25");
        temp.getAnswers().add("15");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Dezimalzahl für den Bruch 3/4?");
        temp.getAnswers().add("0.75");
        temp.getAnswers().add("0.5");
        temp.getAnswers().add("0.25");
        temp.getAnswers().add("1.5");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Summe der ersten 10 natürlichen Zahlen?");
        temp.getAnswers().add("55");
        temp.getAnswers().add("45");
        temp.getAnswers().add("50");
        temp.getAnswers().add("60");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie nennt man eine Zahl, die sich durch 2 ohne Rest teilen lässt?");
        temp.getAnswers().add("Gerade Zahl");
        temp.getAnswers().add("Ungerade Zahl");
        temp.getAnswers().add("Primzahl");
        temp.getAnswers().add("Quadratzahl");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die nächste Zahl in der Reihe: 2, 5, 10, 17, ...?");
        temp.getAnswers().add("26");
        temp.getAnswers().add("27");
        temp.getAnswers().add("21");
        temp.getAnswers().add("18");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Formel für den Umfang eines Kreises?");
        temp.getAnswers().add("2 * Pi * Radius");
        temp.getAnswers().add("Pi * Durchmesser");
        temp.getAnswers().add("Pi * Radius^2");
        temp.getAnswers().add("2 * Pi * Durchmesser");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Summe der Winkel in einem Viereck?");
        temp.getAnswers().add("360 Grad");
        temp.getAnswers().add("180 Grad");
        temp.getAnswers().add("90 Grad");
        temp.getAnswers().add("270 Grad");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Formel für den Satz des Pythagoras?");
        temp.getAnswers().add("a^2 + b^2 = c^2");
        temp.getAnswers().add("a + b = c");
        temp.getAnswers().add("a^2 - b^2 = c^2");
        temp.getAnswers().add("a * b = c^2");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche ist die kleinste Primzahl?");
        temp.getAnswers().add("2");
        temp.getAnswers().add("1");
        temp.getAnswers().add("3");
        temp.getAnswers().add("5");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie nennt man eine Zahl, die größer ist als 1 und nur durch 1 und sich selbst ohne Rest teilbar ist?");
        temp.getAnswers().add("Primzahl");
        temp.getAnswers().add("Zusammengesetzte Zahl");
        temp.getAnswers().add("Gerade Zahl");
        temp.getAnswers().add("Ungerade Zahl");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist das Ergebnis von 9 / 3?");
        temp.getAnswers().add("3");
        temp.getAnswers().add("6");
        temp.getAnswers().add("4");
        temp.getAnswers().add("2");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche ist die größte zweistellige Primzahl?");
        temp.getAnswers().add("97");
        temp.getAnswers().add("89");
        temp.getAnswers().add("101");
        temp.getAnswers().add("83");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Löse die Gleichung: 3x - 7 = 14");
        temp.getAnswers().add("7");
        temp.getAnswers().add("6");
        temp.getAnswers().add("5");
        temp.getAnswers().add("8");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist die Summe der Winkel in einem gleichschenkligen Dreieck?");
        temp.getAnswers().add("180 Grad");
        temp.getAnswers().add("90 Grad");
        temp.getAnswers().add("60 Grad");
        temp.getAnswers().add("120 Grad");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Formel für das Volumen eines Würfels?");
        temp.getAnswers().add("Kantenlänge^3");
        temp.getAnswers().add("6 * Kantenlänge");
        temp.getAnswers().add("Länge * Breite * Höhe");
        temp.getAnswers().add("2 * (Länge + Breite + Höhe)");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche ist die nächste Primzahl nach 31?");
        temp.getAnswers().add("37");
        temp.getAnswers().add("29");
        temp.getAnswers().add("41");
        temp.getAnswers().add("33");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wie lautet die Dezimalzahl für den Bruch 5/8?");
        temp.getAnswers().add("0.625");
        temp.getAnswers().add("0.75");
        temp.getAnswers().add("0.5");
        temp.getAnswers().add("0.875");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist das Produkt von 6 und 9?");
        temp.getAnswers().add("54");
        temp.getAnswers().add("45");
        temp.getAnswers().add("63");
        temp.getAnswers().add("72");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche ist die kleinste positive ganze Zahl?");
        temp.getAnswers().add("1");
        temp.getAnswers().add("0");
        temp.getAnswers().add("2");
        temp.getAnswers().add("3");
        fullPool.add(temp);
    }
    public static void historyLoader() {
        Question temp = new Question();
        temp.setQuestion("In welchem Jahr endete der Erste Weltkrieg?");
        temp.getAnswers().add("1918");                                  //correct answer first!!
        temp.getAnswers().add("1919");
        temp.getAnswers().add("1920");
        temp.getAnswers().add("1917");
        fullPool.add(temp);

        //copy following code for new question:
        temp = new Question();
        temp.setQuestion("Wer war der erste Präsident der Vereinigten Staaten?");
        temp.getAnswers().add("George Washington");
        temp.getAnswers().add("Thomas Jefferson");
        temp.getAnswers().add("John Adams");
        temp.getAnswers().add("Abraham Lincoln");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Ereignis markiert den Beginn des Zweiten Weltkriegs?");
        temp.getAnswers().add("Der deutsche Überfall auf Polen");
        temp.getAnswers().add("Die Bombardierung von Pearl Harbor");
        temp.getAnswers().add("Der Anschluss Österreichs");
        temp.getAnswers().add("Der Einmarsch in die Tschechoslowakei");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war die Königin von Ägypten, die sich auf den Feldzügen mit Julius Caesar und Marcus Antonius verbündete?");
        temp.getAnswers().add("Kleopatra");
        temp.getAnswers().add("Nofretete");
        temp.getAnswers().add("Hatschepsut");
        temp.getAnswers().add("Tiye");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Herrscher führte die mongolische Eroberung und gründete das Mongolische Reich im 13. Jahrhundert?");
        temp.getAnswers().add("Dschingis Khan");
        temp.getAnswers().add("Kublai Khan");
        temp.getAnswers().add("Timur");
        temp.getAnswers().add("Batu Khan");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Jahrzehnt wurde die Berliner Mauer errichtet?");
        temp.getAnswers().add("1960er");
        temp.getAnswers().add("1950er");
        temp.getAnswers().add("1970er");
        temp.getAnswers().add("1980er");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Stadt wurde während des Trojanischen Krieges zerstört?");
        temp.getAnswers().add("Troja");
        temp.getAnswers().add("Athen");
        temp.getAnswers().add("Sparta");
        temp.getAnswers().add("Rom");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der erste Kaiser des Römischen Reiches?");
        temp.getAnswers().add("Augustus");
        temp.getAnswers().add("Julius Caesar");
        temp.getAnswers().add("Nero");
        temp.getAnswers().add("Caligula");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Ereignis markiert das Ende des Römischen Reiches im Jahr 476 n. Chr.?");
        temp.getAnswers().add("Die Absetzung des letzten Kaisers");
        temp.getAnswers().add("Der Fall von Rom");
        temp.getAnswers().add("Die Schlacht von Adrianopel");
        temp.getAnswers().add("Die Völkerwanderung");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der Hauptführer der indischen Unabhängigkeitsbewegung?");
        temp.getAnswers().add("Mahatma Gandhi");
        temp.getAnswers().add("Jawaharlal Nehru");
        temp.getAnswers().add("Subhas Chandra Bose");
        temp.getAnswers().add("Bhagat Singh");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Krieg wird als der Erste Punische Krieg bezeichnet?");
        temp.getAnswers().add("Der Krieg zwischen Rom und Karthago");
        temp.getAnswers().add("Der Peloponnesische Krieg");
        temp.getAnswers().add("Der Trojanische Krieg");
        temp.getAnswers().add("Der Perserkrieg");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der Führer der Bolschewiki während der Russischen Revolution im Jahr 1917?");
        temp.getAnswers().add("Wladimir Lenin");
        temp.getAnswers().add("Josef Stalin");
        temp.getAnswers().add("Leon Trotzki");
        temp.getAnswers().add("Nikolai Bucharin");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Jahr wurde die Magna Carta unterzeichnet?");
        temp.getAnswers().add("1215");
        temp.getAnswers().add("1300");
        temp.getAnswers().add("1150");
        temp.getAnswers().add("1250");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der erste Mensch, der die Antarktis erreichte?");
        temp.getAnswers().add("Roald Amundsen");
        temp.getAnswers().add("Ernest Shackleton");
        temp.getAnswers().add("Robert Falcon Scott");
        temp.getAnswers().add("James Cook");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Kaiser regierte während der Pax Romana, einer Zeit des Friedens und der Stabilität im Römischen Reich?");
        temp.getAnswers().add("Kaiser Augustus");
        temp.getAnswers().add("Kaiser Nero");
        temp.getAnswers().add("Kaiser Trajan");
        temp.getAnswers().add("Kaiser Konstantin");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der Architekt der Akropolis in Athen?");
        temp.getAnswers().add("Phidias");
        temp.getAnswers().add("Iktinos");
        temp.getAnswers().add("Callicrates");
        temp.getAnswers().add("Perikles");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche berühmte Rede hielt Martin Luther King Jr. 1963 vor dem Lincoln Memorial?");
        temp.getAnswers().add("I Have a Dream");
        temp.getAnswers().add("Give Me Liberty or Give Me Death");
        temp.getAnswers().add("We Shall Overcome");
        temp.getAnswers().add("Tear Down This Wall");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der letzte Pharao des antiken Ägypten?");
        temp.getAnswers().add("Kleopatra");
        temp.getAnswers().add("Tutanchamun");
        temp.getAnswers().add("Ramses II");
        temp.getAnswers().add("Nofretete");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Ereignis löste den Beginn des Ersten Weltkriegs aus?");
        temp.getAnswers().add("Die Ermordung von Erzherzog Franz Ferdinand");
        temp.getAnswers().add("Die Invasion Polens");
        temp.getAnswers().add("Die Bombardierung von Pearl Harbor");
        temp.getAnswers().add("Der Angriff auf die Sowjetunion");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welchem Jahr wurde die Unabhängigkeit der Vereinigten Staaten erklärt?");
        temp.getAnswers().add("1776");
        temp.getAnswers().add("1789");
        temp.getAnswers().add("1800");
        temp.getAnswers().add("1750");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der letzte Kaiser von Russland?");
        temp.getAnswers().add("Nikolaus II.");
        temp.getAnswers().add("Alexander II.");
        temp.getAnswers().add("Peter der Große");
        temp.getAnswers().add("Iwan der Schreckliche");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Ereignis wird oft als der Beginn der Renaissance angesehen?");
        temp.getAnswers().add("Fall von Konstantinopel");
        temp.getAnswers().add("Entdeckung Amerikas");
        temp.getAnswers().add("Ausbruch der Pest");
        temp.getAnswers().add("Ende des Hundertjährigen Krieges");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer war der erste Mensch, der den Mond betrat?");
        temp.getAnswers().add("Neil Armstrong");
        temp.getAnswers().add("Buzz Aldrin");
        temp.getAnswers().add("Yuri Gagarin");
        temp.getAnswers().add("Michael Collins");
        fullPool.add(temp);
    }
    public static void biologyLoader() {
        Question temp = new Question();
        temp.setQuestion("Welche Art von Zellen führt Photosynthese durch?");
        temp.getAnswers().add("Pflanzenzellen");                //correct answer first!!
        temp.getAnswers().add("Chloroplasten");
        temp.getAnswers().add("Tierzellen");
        temp.getAnswers().add("Bakterienzellen");
        fullPool.add(temp);

        //copy following code for new questions:
        temp = new Question();
        temp.setQuestion("Welches ist das größte Säugetier auf der Erde?");
        temp.getAnswers().add("Blauwal");
        temp.getAnswers().add("Elefant");
        temp.getAnswers().add("Giraffe");
        temp.getAnswers().add("Nashorn");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist der Hauptbestandteil der Zellmembran?");
        temp.getAnswers().add("Phospholipide");
        temp.getAnswers().add("Proteine");
        temp.getAnswers().add("Cholesterin");
        temp.getAnswers().add("Zucker");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Organ ist für die Produktion von Insulin verantwortlich?");
        temp.getAnswers().add("Bauchspeicheldrüse");
        temp.getAnswers().add("Leber");
        temp.getAnswers().add("Niere");
        temp.getAnswers().add("Herz");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Blutzellen sind für die Immunabwehr verantwortlich?");
        temp.getAnswers().add("Weiße Blutkörperchen");
        temp.getAnswers().add("Rote Blutkörperchen");
        temp.getAnswers().add("Blutplättchen");
        temp.getAnswers().add("Plasmazellen");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Tier ist für seine Fähigkeit zur Tarnung bekannt?");
        temp.getAnswers().add("Kamäleon");
        temp.getAnswers().add("Oktopus");
        temp.getAnswers().add("Schneehase");
        temp.getAnswers().add("Leopard");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Pflanze ist bekannt für ihre heilenden Eigenschaften und wird oft in der Aromatherapie verwendet?");
        temp.getAnswers().add("Lavendel");
        temp.getAnswers().add("Eukalyptus");
        temp.getAnswers().add("Kamille");
        temp.getAnswers().add("Rosmarin");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist der Hauptbestandteil von menschlichen Knochen?");
        temp.getAnswers().add("Calciumphosphat");
        temp.getAnswers().add("Eisen");
        temp.getAnswers().add("Kollagen");
        temp.getAnswers().add("Kaliumsulfat");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Hormon wird von der Schilddrüse produziert?");
        temp.getAnswers().add("Thyroxin");
        temp.getAnswers().add("Insulin");
        temp.getAnswers().add("Adrenalin");
        temp.getAnswers().add("Östrogen");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Organ im menschlichen Körper produziert Bilirubin?");
        temp.getAnswers().add("Leber");
        temp.getAnswers().add("Niere");
        temp.getAnswers().add("Darm");
        temp.getAnswers().add("Magen");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Teil des Gehirns ist für die Koordination von Bewegungen verantwortlich?");
        temp.getAnswers().add("Kleinhirn");
        temp.getAnswers().add("Großhirn");
        temp.getAnswers().add("Hirnstamm");
        temp.getAnswers().add("Limbisches System");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist der Hauptbestandteil von menschlichem Blut?");
        temp.getAnswers().add("Plasma");
        temp.getAnswers().add("Blutzellen");
        temp.getAnswers().add("Hämoglobin");
        temp.getAnswers().add("Serum");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Teil der Blütenpflanze produziert Pollen?");
        temp.getAnswers().add("Staubblatt");
        temp.getAnswers().add("Kelchblatt");
        temp.getAnswers().add("Kronblatt");
        temp.getAnswers().add("Fruchtblatt");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Enzym spaltet Fette während der Verdauung?");
        temp.getAnswers().add("Lipase");
        temp.getAnswers().add("Amylase");
        temp.getAnswers().add("Protease");
        temp.getAnswers().add("Nuclease");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Vitamin wird durch Sonnenlicht in der Haut produziert?");
        temp.getAnswers().add("Vitamin D");
        temp.getAnswers().add("Vitamin C");
        temp.getAnswers().add("Vitamin A");
        temp.getAnswers().add("Vitamin K");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Vogel ist für seine nachahmenden Fähigkeiten bekannt?");
        temp.getAnswers().add("Papagei");
        temp.getAnswers().add("Nachtigall");
        temp.getAnswers().add("Eule");
        temp.getAnswers().add("Spatz");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Organell ist für die Umwandlung von Nährstoffen in Energie in der Zelle verantwortlich?");
        temp.getAnswers().add("Mitochondrium");
        temp.getAnswers().add("Chloroplast");
        temp.getAnswers().add("Endoplasmatisches Retikulum");
        temp.getAnswers().add("Lysosom");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Was ist der Hauptbestandteil der Zellwände von Pflanzenzellen?");
        temp.getAnswers().add("Zellulose");
        temp.getAnswers().add("Chitin");
        temp.getAnswers().add("Pektin");
        temp.getAnswers().add("Lignin");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches ist das größte lebende Reptil?");
        temp.getAnswers().add("Krokodil");
        temp.getAnswers().add("Schildkröte");
        temp.getAnswers().add("Echse");
        temp.getAnswers().add("Schlange");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Tier ist für seine Winterschlaf-Fähigkeiten bekannt?");
        temp.getAnswers().add("Igel");
        temp.getAnswers().add("Bär");
        temp.getAnswers().add("Eichhörnchen");
        temp.getAnswers().add("Fledermaus");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches ist das größte lebende Wirbeltier?");
        temp.getAnswers().add("Blauwal");
        temp.getAnswers().add("Elefant");
        temp.getAnswers().add("Giraffe");
        temp.getAnswers().add("Nashorn");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Blume wird oft mit Frühling und Erneuerung assoziiert?");
        temp.getAnswers().add("Krokus");
        temp.getAnswers().add("Lilie");
        temp.getAnswers().add("Sonnenblume");
        temp.getAnswers().add("Tulpe");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Bestandteil des Blutes ist für den Sauerstofftransport verantwortlich?");
        temp.getAnswers().add("Hämoglobin");
        temp.getAnswers().add("Plasma");
        temp.getAnswers().add("Blutzellen");
        temp.getAnswers().add("Serum");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Art von Gewebe verbindet Knochen mit Knochen?");
        temp.getAnswers().add("Binde- oder Bindegewebe");
        temp.getAnswers().add("Muskelgewebe");
        temp.getAnswers().add("Nervengewebe");
        temp.getAnswers().add("Epithelgewebe");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Tier ist für seine erstaunlichen Wanderungen bekannt?");
        temp.getAnswers().add("Monarchfalter");
        temp.getAnswers().add("Wilde Gnuherde");
        temp.getAnswers().add("Grauwal");
        temp.getAnswers().add("Gepard");
        fullPool.add(temp);
    }

    public static void popcultureLoader() {
        Question temp = new Question();
        temp.setQuestion("Wer gewann den Oscar als beste Schauspielerin für ihre Rolle in 'La La Land'?");
        temp.getAnswers().add("Emma Stone");                        //correct answer first!!
        temp.getAnswers().add("Natalie Portman");
        temp.getAnswers().add("Jennifer Lawrence");
        temp.getAnswers().add("Cate Blanchett");
        fullPool.add(temp);

        //copy following code to add new question:
        temp = new Question();
        temp.setQuestion("In welcher TV-Serie spielt Kit Harington die Rolle von Jon Snow?");
        temp.getAnswers().add("Game of Thrones");
        temp.getAnswers().add("Breaking Bad");
        temp.getAnswers().add("The Walking Dead");
        temp.getAnswers().add("Stranger Things");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Superheld wird von Robert Downey Jr. im Marvel Cinematic Universe gespielt?");
        temp.getAnswers().add("Iron Man");
        temp.getAnswers().add("Captain America");
        temp.getAnswers().add("Thor");
        temp.getAnswers().add("Hulk");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Künstler ist für Hits wie 'Shape of You' und 'Thinking Out Loud' bekannt?");
        temp.getAnswers().add("Ed Sheeran");
        temp.getAnswers().add("Justin Bieber");
        temp.getAnswers().add("Adele");
        temp.getAnswers().add("Taylor Swift");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Serie handelt von einem Chemielehrer, der Methamphetamin herstellt?");
        temp.getAnswers().add("Breaking Bad");
        temp.getAnswers().add("The Sopranos");
        temp.getAnswers().add("Dexter");
        temp.getAnswers().add("The Wire");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Film gewann den Oscar für den besten Film im Jahr 2020?");
        temp.getAnswers().add("Parasite");
        temp.getAnswers().add("Joker");
        temp.getAnswers().add("1917");
        temp.getAnswers().add("Once Upon a Time in Hollywood");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Band ist für Hits wie 'Stairway to Heaven' und 'Whole Lotta Love' bekannt?");
        temp.getAnswers().add("Led Zeppelin");
        temp.getAnswers().add("The Rolling Stones");
        temp.getAnswers().add("The Beatles");
        temp.getAnswers().add("Queen");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer ist der Schöpfer der TV-Serie 'The Office'?");
        temp.getAnswers().add("Ricky Gervais");
        temp.getAnswers().add("Steve Carell");
        temp.getAnswers().add("John Krasinski");
        temp.getAnswers().add("Greg Daniels");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Videospiel-Franchise enthält Charaktere wie Mario, Luigi und Princess Peach?");
        temp.getAnswers().add("Super Mario Bros.");
        temp.getAnswers().add("The Legend of Zelda");
        temp.getAnswers().add("Pokemon");
        temp.getAnswers().add("Final Fantasy");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Schauspieler spielt die Hauptrolle in der 'John Wick'-Filmreihe?");
        temp.getAnswers().add("Keanu Reeves");
        temp.getAnswers().add("Tom Hardy");
        temp.getAnswers().add("Liam Neeson");
        temp.getAnswers().add("Brad Pitt");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("In welcher TV-Serie kämpfen die Starks und die Lannisters um den Eisernen Thron?");
        temp.getAnswers().add("Game of Thrones");
        temp.getAnswers().add("Vikings");
        temp.getAnswers().add("The Tudors");
        temp.getAnswers().add("The Witcher");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Künstler ist als 'The King of Pop' bekannt?");
        temp.getAnswers().add("Michael Jackson");
        temp.getAnswers().add("Elvis Presley");
        temp.getAnswers().add("Prince");
        temp.getAnswers().add("Madonna");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Schauspielerin spielt die Rolle von Katniss Everdeen in 'Die Tribute von Panem'?");
        temp.getAnswers().add("Jennifer Lawrence");
        temp.getAnswers().add("Emma Watson");
        temp.getAnswers().add("Shailene Woodley");
        temp.getAnswers().add("Scarlett Johansson");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Film von Quentin Tarantino handelt von einem Kopfgeldjäger im Wilden Westen?");
        temp.getAnswers().add("Django Unchained");
        temp.getAnswers().add("Pulp Fiction");
        temp.getAnswers().add("Kill Bill");
        temp.getAnswers().add("Inglourious Basterds");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Song von Beyoncé war in den Charts mit dem Text 'All the single ladies'?");
        temp.getAnswers().add("Single Ladies (Put a Ring on It)");
        temp.getAnswers().add("Irreplaceable");
        temp.getAnswers().add("Crazy in Love");
        temp.getAnswers().add("Halo");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Videospiel-Franchise enthält Charaktere wie Master Chief und Cortana?");
        temp.getAnswers().add("Halo");
        temp.getAnswers().add("Call of Duty");
        temp.getAnswers().add("Fortnite");
        temp.getAnswers().add("Overwatch");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer spielt die Hauptrolle in der 'Harry Potter'-Filmreihe?");
        temp.getAnswers().add("Daniel Radcliffe");
        temp.getAnswers().add("Rupert Grint");
        temp.getAnswers().add("Emma Watson");
        temp.getAnswers().add("Tom Felton");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche TV-Serie handelt von einer Gruppe Überlebender in einer Zombie-Apokalypse?");
        temp.getAnswers().add("The Walking Dead");
        temp.getAnswers().add("Stranger Things");
        temp.getAnswers().add("Breaking Bad");
        temp.getAnswers().add("Game of Thrones");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Künstler veröffentlichte das Album 'Thriller' im Jahr 1982?");
        temp.getAnswers().add("Michael Jackson");
        temp.getAnswers().add("Prince");
        temp.getAnswers().add("Madonna");
        temp.getAnswers().add("David Bowie");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Film von Christopher Nolan handelt von Träumen und Realität?");
        temp.getAnswers().add("Inception");
        temp.getAnswers().add("Interstellar");
        temp.getAnswers().add("The Prestige");
        temp.getAnswers().add("Dunkirk");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welche Band ist für Hits wie 'Bohemian Rhapsody' und 'We Will Rock You' bekannt?");
        temp.getAnswers().add("Queen");
        temp.getAnswers().add("The Beatles");
        temp.getAnswers().add("Led Zeppelin");
        temp.getAnswers().add("The Rolling Stones");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer spielt die Hauptrolle in der 'Wonder Woman'-Filmreihe?");
        temp.getAnswers().add("Gal Gadot");
        temp.getAnswers().add("Scarlett Johansson");
        temp.getAnswers().add("Brie Larson");
        temp.getAnswers().add("Angelina Jolie");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Künstler gewann den Grammy Award für das Album des Jahres im Jahr 2021 mit 'Folklore'?");
        temp.getAnswers().add("Taylor Swift");
        temp.getAnswers().add("Beyoncé");
        temp.getAnswers().add("Dua Lipa");
        temp.getAnswers().add("Billie Eilish");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welcher Künstler ist für Hits wie 'Blinding Lights' und 'Can't Feel My Face' bekannt?");
        temp.getAnswers().add("The Weeknd");
        temp.getAnswers().add("Drake");
        temp.getAnswers().add("Kanye West");
        temp.getAnswers().add("Bruno Mars");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Welches Videospiel-Franchise enthält Charaktere wie Link und Princess Zelda?");
        temp.getAnswers().add("The Legend of Zelda");
        temp.getAnswers().add("Super Mario Bros.");
        temp.getAnswers().add("Final Fantasy");
        temp.getAnswers().add("Minecraft");
        fullPool.add(temp);

        temp = new Question();
        temp.setQuestion("Wer gewann den Oscar als beste Schauspielerin für ihre Rolle in 'Black Swan'?");
        temp.getAnswers().add("Natalie Portman");
        temp.getAnswers().add("Meryl Streep");
        temp.getAnswers().add("Cate Blanchett");
        temp.getAnswers().add("Julianne Moore");
        fullPool.add(temp);
    }





    /*public DataRepository() {
        _anwsers = fetchAnwsersfromDB();
    }

    public List<Answer> fetchAnwsersfromDB(){

        // Initialize the connection
        try {
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

            if (connection != null) {
                System.out.println("Connected to the database!");

                // You can now perform database operations using the 'connection' object.
                // For example, you can execute SQL queries, insert, update, or delete records.

                // Don't forget to close the connection when done.
                connection.close();
            } else {
                System.out.println("Failed to connect to the database!");
            }
        } catch (SQLException e) {
            System.err.println("Database connection error: " + e.getMessage());
        }


        return mockAnwsers();



    public List<Answer> mockAnwsers(){
        List<Answer> _anwsers = new ArrayList<>();

        Answer a1 = new Answer();
        a1.setAnwser("Europa");
        a1.setId(1);
        a1.setCorrect(true);
        a1.setFk_question_id(1);

        Answer a2 = new Answer();
        a2.setAnwser("Asien");
        a2.setId(2);
        a2.setCorrect(false);
        a2.setFk_question_id(1);

        Answer a3 = new Answer();
        a3.setAnwser("Afrika");
        a3.setId(3);
        a3.setCorrect(false);
        a3.setFk_question_id(1);

        Answer a4 = new Answer();
        a4.setAnwser("Nordamerika");
        a4.setId(4);
        a4.setCorrect(false);
        a4.setFk_question_id(1);

        _anwsers.add(a1);
        _anwsers.add(a2);
        _anwsers.add(a3);
        _anwsers.add(a4);
        return _anwsers;
    }

 */
}
